---
- name: Site Down
  hosts: web
  gather_facts: false
  become: true
  
  tasks:
    - debug:
        msg: "Website is down!"

    - name: Replace website
      copy:
        content: "Hello from {{ ansible_distribution }} {{ ansible_distribution_version }}"
        dest: /var/www/html/index.html
        owner: apache
        group: apache
        mode: '0644'