---
- name: Listen for events on a webhook
  hosts: all
  ## Define our source for events
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  ## Define the conditions we are looking for
  rules:
    - name: Say Hello
      condition: event.payload.message == "Ansible is super cool"
  ## Define the action we should take should the condition be met
      action:
        run_playbook:
          name: say-what.yml

    - name: Check for configuration drift
      condition: event.payload.event_type == "drift-baseline-detected"

      action:
        run_playbook:
        name: remediate-drift.yml

        debug:
          msg: "!!!!!!!!!!!!!!!!System Drift Detected"

    - name: Handle Red Hat Insights event
      condition: event.payload is defined

      action:
        debug:
          msg: "Received: {{ event.payload }}"

